name: 'scannet_selfsup_view3'
arch:
    max_epochs: 100
checkpoint:
    save_top_k: 10
    monitor: 'abs_rel_pp_gt'
    monitor_index: 0
model:
    name: 'SelfSupModelMF'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthPoseNet'
        version: 'it12-h-out'
    loss: 
        automask_loss: True
        photometric_reduce_op: 'min'
    params:
        crop: ''
        min_depth: 0.2
        max_depth: 10.0
datasets:
    augmentation:
        image_shape: (320, 512)
    train:
        batch_size: 3
        dataset: ['ScannetBA']
        # path: ['/data/datasets/scannet/train']
        path: ['/opt/slam/scannet/train']
        split: ['splits/train_all_list.txt']
        depth_type: ['groundtruth']
        repeat: [1]
        forward_context: 1
        back_context: 1
    validation:
        dataset: ['ScannetTest']
        # path: ['/data/datasets/scannet/test']
        path: ['/opt/slam/scannet/test']
        split: ['splits/test_split.txt']
        depth_type: ['groundtruth']
        forward_context: 1
        back_context: 1
    test:
        dataset: ['ScannetTest']
        # path: ['/data/datasets/scannet/test']
        path: ['/opt/slam/scannet/test']
        split: ['splits/test_split.txt']
        depth_type: ['groundtruth']
        forward_context: 1
        back_context: 1
