# ref: train_scannet_mf_gt_view2.yaml
name: 'matterport_gt'
save:
    folder: './results'
arch:
    max_epochs: 100
checkpoint:
    save_top_k: 10
    monitor: 'abs_rel_pp_gt'
    monitor_index: 0
model:
    name: 'SupModelMF'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthPoseNet'
        version: 'it12-h-out'
    loss: 
        automask_loss: True
        photometric_reduce_op: 'min'
    params:
        crop: ''
        min_depth: 0.2
        max_depth: 10.0
datasets:
    augmentation:
        image_shape: (240, 320)
    train:
        batch_size: 12
        dataset: ['Matterport']
        # xuelian_yang@badger
        # path: ['/home/xuelian_yang/slam/matterport']
        # xuelian@fox
        path: ['/home/xuelian/slam/matterport']
        split: ['splits/train_tiny_list.txt']
        depth_type: ['groundtruth']
        repeat: [1]
        forward_context: 1
        back_context: 0
        num_workers: 32
    validation:
        dataset: ['MatterportTest']
        # xuelian_yang@badger
        # path: ['/home/xuelian_yang/slam/matterport']
        # xuelian@fox
        path: ['/home/xuelian/slam/matterport']
        split: ['splits/val_tiny_list.txt']
        depth_type: ['groundtruth']
        forward_context: 1
        back_context: 0
    test:
        dataset: ['MatterportTest']
        # xuelian_yang@badger
        # path: ['/home/xuelian_yang/slam/matterport']
        # xuelian@fox
        path: ['/home/xuelian/slam/matterport']
        split: ['splits/test_tiny_list.txt']
        depth_type: ['groundtruth']
        forward_context: 1
        back_context: 0
